import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  index("routes/home.tsx"),
  route("sign-in", "routes/sign-in.tsx"),
  route("sign-up", "routes/sign-up.tsx"),
  route("forgot-password", "routes/forgot-password.tsx"),
  route("reset-password", "routes/reset-password.tsx"),
  route("account", "routes/account.tsx"),
  route("upload", "routes/upload.tsx"),
  route("analyze/:id", "routes/analyze.$id.tsx"),
  route("api/resumes", "routes/api.resumes.tsx"),
  route("api/upload", "routes/api.upload.tsx"),
  route("api/analyze", "routes/api.analyze.tsx"),
  route("api/update-resume", "routes/api.update-resume.tsx"),
  route("api/save-resume", "routes/api.save-resume.tsx"),
  route("api/test-db", "routes/api.test-db.tsx"),
  route("api/auth/signup", "routes/api.auth.signup.tsx"),
  route("api/auth/signin", "routes/api.auth.signin.tsx"),
  route("api/auth/signout", "routes/api.auth.signout.tsx"),
  route("api/auth/me", "routes/api.auth.me.tsx"),
  route("api/auth/update-profile", "routes/api.auth.update-profile.tsx"),
  route("api/auth/forgot-password", "routes/api.auth.forgot-password.tsx"),
  route("api/auth/reset-password", "routes/api.auth.reset-password.tsx"),
  route("api/auth/google", "routes/api.auth.google.tsx"),
  route("api/auth/google/callback", "routes/api.auth.google.callback.tsx"),
  route("api/auth/google/disconnect", "routes/api.auth.google.disconnect.tsx"),
  route("api/migrate-auth", "routes/api.migrate-auth.tsx"),
  route("api/migrate-password-reset", "routes/api.migrate-password-reset.tsx"),
  route("api/migrate-oauth", "routes/api.migrate-oauth.tsx"),
] satisfies RouteConfig;
